feat: simplification Renderer->columnOptions output for datetime now
cycle/migrations pull request #33
Opened 2022-03-08 21:59 UTC by aquaminer

Before
```php
            ->addColumn('created_at', 'datetime', [
                'nullable' => false,
                'default'  => \Cycle\Database\Injection\Fragment::__set_state(array(
               'fragment' => 'now()',
               'parameters' =>
              array (
                ),
                ))
            ])
```
After
```php
            ->addColumn('created_at', 'datetime', [
                'nullable' => false,
                'default'  => 'CURRENT_TIMESTAMP'
               )
            ])
```

CURRENT_TIMESTAMP will be translated for postgresql to now() in [AbstractColumn (cycle/database)](https://github.com/cycle/database/blob/2.x/src%2FSchema%2FAbstractColumn.php#L490)

2022-03-09 15:05 UTC, msmakouz requested changes

2022-03-09 15:05 UTC, msmakouz commented on src/Atomizer/Renderer.php
> +        if ($options['default'] == $column::DATETIME_NOW) {
I recommend adding a strict comparison here (===).

It might be worth adding a test with new functionality. What do you think? @roxblnfk

2022-03-09 17:59 UTC, aquaminer commented on src/Atomizer/Renderer.php
> +        if ($options['default'] == $column::DATETIME_NOW) {
if use strict comparison here, before/after example don't be work (because Fragment does not converted to string).

2022-03-09 18:00 UTC, aquaminer commented
i don't have ideas for testing this functionality. Poor test ⬆️

2022-03-10 14:21 UTC, msmakouz commented on src/Atomizer/Renderer.php
> +        if ($options['default'] == $column::DATETIME_NOW) {
Perhaps it is better to check the type, cast to the needed type, and compare? If it doesn't add a lot of code.

2022-03-10 15:04 UTC, roxblnfk commented on src/Atomizer/Renderer.php
> +        if ($options['default'] === $column::DATETIME_NOW || ($options['default'] instanceof Fragment && (string)$options['default'] === $column::DATETIME_NOW)) {
```suggestion
        $default = $options['default'];
        if ($column::DATETIME_NOW === ($default instanceof \Stringable ? (string)$default : $default)) {
```

I think this fragment is little prettier :)

2022-03-10 15:13 UTC, msmakouz approved these changes

2022-03-10 20:00 UTC, merged

2022-03-10 20:01 UTC, roxblnfk commented
Thank you!